CREATE DATABASE miushi
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

USE miushi;

CREATE TABLE categories (
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`name` VARCHAR(64) NOT NULL,
PRIMARY KEY (`id`)
);

CREATE TABLE catalog (
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`url` VARCHAR(255) NOT NULL,
`quantity` VARCHAR(64) DEFAULT NULL,
`weight` INT UNSIGNED NOT NULL,
`calorie` INT UNSIGNED NOT NULL,
`price` INT UNSIGNED NOT NULL,
`catalog_name` VARCHAR(255) NOT NULL,
`stock` VARCHAR(64) DEFAULT NULL,
`hit` VARCHAR(64) DEFAULT NULL,
`new` VARCHAR(64) DEFAULT NULL,
`veg` VARCHAR(64) DEFAULT NULL,
`category_id` INT UNSIGNED NOT NULL,
PRIMARY KEY (`id`)
);

CREATE TABLE sauce (
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`price` INT UNSIGNED NOT NULL,   //цена
`name` VARCHAR(255) NOT NULL,  //название товара
PRIMARY KEY (`id`),
UNIQUE key `name`(`name`)
);

CREATE TABLE basket (
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`date_creation` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
`name` VARCHAR(255) NOT NULL,
`price` VARCHAR(255) NOT NULL,
`token`VARCHAR(64) DEFAULT NULL,
PRIMARY KEY (`id`),
UNIQUE KEY `name`(`name`)
);

/*
//создание индекса для поля
CREATE FULLTEXT INDEX task_search ON tasks(name)
*/
